spring:
  application:
    name: custom-gateway
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    port: 6379
    host: 127.0.0.1
#    password: 123456
    jedis:
      pool:
        max-active: 1000
        min-idle: 5
        max-wait: 6000
        max-idle: 18
  cache:
    type: caffeine
    caffeine:
      spec: initialCapacity=10,maximumSize=2000,expireAfterWrite=6s

server:
  port: 1012

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1001/eureka/
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
    health-check-url-path: /actuator/health
    metadata-map:
      user:
        name: admin
        password: admin

feign:
  httpclient:
    enabled: true
  hystrix:
    enabled: true
ribbon:
  ReadTimeout: 1000
  ConnectTimeout: 1000
  MaxAutoRetries: 1   #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试
  MaxAutoRetriesNextServer: 1 #切换实例的重试次数
  OkToRetryOnAllOperations: false #对所有的操作请求都进行重试，如果是get则可以，如果是post,put等操作没有实现幂等的情况下是很危险的，所以设置为false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000 # (1 + MaxAutoRetries + MaxAutoRetriesNextServer) * ReadTimeout
    serverMethod:
          execution:
            isolation:
              thread:
                timeoutInMilliseconds: 3000

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator

  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  server:
    port: 1012
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

nacos:
  config:
    server-addr: 127.0.0.1:8848

routeCache:
  enable: true
  balance: true
  server: true
limiting:
  enable: true

pagehelper:
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
  row-bounds-with-count: true
  helper-dialect: mysql


